# Development Environment Docker Compose
# Provides containerized development environment for liquid-audio-nets

version: '3.8'

services:
  # Main development container
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    environment:
      - RUST_LOG=debug
      - CARGO_HOME=/usr/local/cargo
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
    command: tail -f /dev/null

  # Testing container with hardware simulation
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - CI=true
      - RUST_BACKTRACE=1

  # Documentation server
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    volumes:
      - ./docs:/docs
    ports:
      - "8000:8000"
    command: python -m http.server 8000 --directory /docs/_build

volumes:
  cargo-cache:
  target-cache: