# Prometheus configuration for liquid-audio-nets monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Application metrics
  - job_name: 'liquid-audio-nets'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Hardware metrics (for embedded devices)
  - job_name: 'embedded-device'
    static_configs:
      - targets: ['device:8081']
    metrics_path: /device/metrics
    scrape_interval: 10s

  # Training metrics
  - job_name: 'training-metrics'
    static_configs:
      - targets: ['localhost:6006']  # TensorBoard
    metrics_path: /metrics